# Generated by Django 5.1.6 on 2025-03-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('idade', models.CharField(default='', max_length=10)),
                ('level', models.CharField(default='', max_length=100)),
                ('genero', models.CharField(default='', max_length=50)),
                ('departamento', models.CharField(default='', max_length=100)),
                ('raca', models.CharField(default='', max_length=50)),
                ('nacionalidade', models.CharField(default='', max_length=50)),
                ('tipo_colaborador', models.CharField(default='', max_length=50)),
                ('salario', models.CharField(default='', max_length=50)),
                ('data_nascimento', models.DateField()),
                ('data_onbording', models.DateField()),
            ],
        ),
    ]
