# Generated by Django 5.1.6 on 2025-03-06 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='cidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ona.departs'),
        ),
        migrations.CreateModel(
            name='EmailTalks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField()),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_recebidos', to='ona.employee')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_enviados', to='ona.employee')),
            ],
        ),
    ]
