# Generated by Django 5.1.7 on 2025-03-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ona', '0002_departs_employee_cidade_employee_depart_emailtalks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='departamento',
            new_name='lider',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
