# Generated by Django 5.1.7 on 2025-03-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ona', '0003_rename_departamento_employee_lider_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtalks',
            name='hash_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='emailtalks',
            name='origem',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='emailtalks',
            name='tipo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
