# Generated by Django 5.1.7 on 2025-03-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ona', '0005_rename_cidade_employee_estado_remove_emailtalks_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.IntegerField(),
        ),
    ]
